CI: Enable yocto image build triggers to meta-fusion

diff --git a/.github/workflows/Continuous-Integration.yml b/.github/workflows/Continuous-Integration.yml
--- a/.github/workflows/Continuous-Integration.yml
+++ b/.github/workflows/Continuous-Integration.yml
@@ -342,23 +342,45 @@ jobs:
         id: set-output
         run: echo "ran=true" >> $GITHUB_OUTPUT
 
-  yocto-image-build-trigger:
+  integration-tests:
     needs:
-      - buildChecks
-      - fusion-dsp-build
-      - fusion-server-build
-      - fusion-system-monitor-build
-      - fusion-edge-gateway-build
-      - fusion-telemetry-core-build
+      - flutter-android-iOS-macOS
+      - flutter-windows
+      - flutter-web
+      - fusion-dsp
+      - fusion-server
+      - fusion-system-monitor
+      - fusion-edge-gateway
+      - fusion-telemetry-core
 
     if: |
-      always() &&
-      github.ref_name == 'devops/trigger-yocto-build' && (
-        (needs.fusion-dsp-build.result == 'success' && needs.fusion-dsp-build.outputs.ran == 'true') ||
-        (needs.fusion-server-build.result == 'success' && needs.fusion-server-build.outputs.ran == 'true') ||
-        (needs.fusion-system-monitor-build.result == 'success' && needs.fusion-system-monitor-build.outputs.ran == 'true') ||
-        (needs.fusion-edge-gateway-build.result == 'success' && needs.fusion-edge-gateway-build.outputs.ran == 'true') ||
-        (needs.fusion-telemetry-core-build.result == 'success' && needs.fusion-telemetry-core-build.outputs.ran == 'true')
+      always() && (
+        (needs.fusion-dsp.result == 'success' && needs.fusion-dsp.outputs.ran == 'true') ||
+        (needs.fusion-server.result == 'success' && needs.fusion-server.outputs.ran == 'true') ||
+        (needs.fusion-system-monitor.result == 'success' && needs.fusion-system-monitor.outputs.ran == 'true') ||
+        (needs.fusion-edge-gateway.result == 'success' && needs.fusion-edge-gateway.outputs.ran == 'true') ||
+        (needs.fusion-telemetry-core.result == 'success' && needs.fusion-telemetry-core.outputs.ran == 'true')
+      )
+    concurrency:
+      group: integration-tests
+    runs-on: ubuntu-agent
+    outputs:
+      ran: ${{ steps.set-output.outputs.ran }}
+    timeout-minutes: 30
+    steps:
+      - name: Make changes in target repo
+        run: |
+          echo "Integration Tests successful"
+      - name: Set output
+        id: set-output
+        run: echo "ran=true" >> $GITHUB_OUTPUT
+
+  yocto-image-build:
+    needs:
+      - integration-tests
+    if: |
+      always() && (
+        needs.integration-tests.result == 'success' && needs.integration-tests.outputs.ran == 'true'
       )
     concurrency:
       group: yocto-image-build-trigger
@@ -372,12 +394,28 @@ jobs:
           ref: devops/trigger-yocto-build
           token: ${{ secrets.META_FUSION_REPO_TOKEN }}
           fetch-depth: 0
-          
-      - name: Make changes in target repo
+
+      - name: Update fusion config file with branch name
+        env:
+          BRANCH_NAME: ${{ github.ref_name }}
         run: |
-          echo "Build successful on $(date)" >> build-status.txt
-          git add build-status.txt
-          git commit -m "CI: Build success from Fusion monorepo" || echo "No changes to commit"
+          FILE="conf/fusion-mini_properties.inc"
+
+          # Create file if it doesn't exist
+          if [ ! -f "$FILE" ]; then
+            echo "File $FILE does not exist. Failing the step."
+            exit 1
+          else
+            # Replace the line or append it
+            if grep -q "^FUSION_MONOREPO_BRANCH=" "$FILE"; then
+              sed -i "s/^FUSION_MONOREPO_BRANCH=.*/FUSION_MONOREPO_BRANCH=${BRANCH_NAME}/" "$FILE"
+            else
+              echo "FUSION_MONOREPO_BRANCH=${BRANCH_NAME}" >> "$FILE"
+            fi
+          fi
+
+          git add conf/fusion-mini_properties.inc
+          git commit -m "CI: Build trigger from Fusion Monorepo branch: ${{ github.ref_name }}" || echo "No changes to commit"
 
       - name: Push commit to target repo
         run: |
